<?php
/**
 * @package   Mediarox_IdealoTrackingPixel
 * @copyright Copyright 2020 (c) mediarox UG (haftungsbeschraenkt) (http://www.mediarox.de)
 * @author    Marcus Bernt <mbernt@mediarox.de>
 *
 * @var \Magento\Framework\View\Element\Template               $block
 * @var \Mediarox\IdealoTrackingPixel\ViewModel\IdealoTracking $viewModel
 */
?>
<?php $viewModel = $block->getData('mediarox_idealo_tracking_view_model'); ?>
<?php if ($trackingUrl = $viewModel->getIdealoTrackingUrl()) : ?>
    <img alt=""
         id="mediarox_idealo_tracking_pixel"
         src="<?= $block->escapeUrl($trackingUrl) ?>"
         style="display: none"
         width="1"
         height="1">
<?php endif; ?>
